spring.datasource.url=jdbc:mysql://localhost:3306/fortagym?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Andylian129@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8089

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Aumentar el límite de peso para subir imágenes (Hasta 15 MB por foto)
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

# CONFIGURACIÓN LOCAL (DEFAULTS)
file.upload-dir=uploads/
app.backend.url=http://localhost:8089
allowed.origins=http://localhost:4200

# Clave secreta para firmar los tokens JWT
jwt.secret=WansdSystem_Super_Secret_Key_FortaGym_2026_Extremadamente_Larga

springdoc.swagger-ui.layout=BaseLayout