# Configuración de Base de Datos en la Nube (Aiven)
spring.datasource.url=jdbc:mysql://mysql-328a3a74-andersonurrutiamoreyra-85bc.h.aivencloud.com:28203/defaultdb?useSSL=true&requireSSL=false
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_haZx4zOaH-y__n2vbqq
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html


# Aumentar el límite de peso para subir imágenes (Hasta 15 MB por foto)
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB